### ISSUE TITLE
Revisit color assignment for TotalSegmentator results

### ISSUE THREAD

**Issue by fedorov** [ImagingDataCommons/Cloud-Resources-Workflows#10]
Current colors are suboptimal (currently, we rely on this https://github.com/AIM-Harvard/mhub/blob/main/mhub/totalsegmentator/config/dicomseg_metadata_whole.json), since they make it very difficult to spot segmentation errors for adjacent structures (e.g., all of the vertebrae have the same color).

We could assign random distinctive colors, as suggested by @ccosmin97:

>  you could try something like this to generate n 'distinct' colors -- high level python package
```python
from distinctipy import distinctipy
colors = distinctipy.get_colors(104, n_attempts=1000)
print(colors)
# display the colours
distinctipy.color_swatch(colors)
```

> the rgb tuples are normalized, so you would need to *255 for the field RecommendedRGBDisplayValue in dcmqi.json
> A more involved discussion here https://stackoverflow.com/questions/470690/how-to-automatically-generate-n-distinct-colors

but they may not be "pleasing" to eye and may not follow the same palette. Also, we may want to somehow assign the colors to vertebrae in a way that allows to differentiate between different vertebrae levels, as in the below:

![image](https://github.com/ImagingDataCommons/Cloud-Resources-Workflows/assets/313942/c1ab31aa-cdf8-4113-a314-011e76b27b92)

@pieper mentioned there are some color label maps that were used in other projects. Can you provide references to those Steve?

We should also review what is available in the SPL atlas and reuse colors for organs, if they do not have individual vertebrae (maybe that is also something that Andras already did for the TotalSegmentator extension).

We should also assign same color to the left-right structures, but different colors to different levels (for ribs, for example).

FYI @lassoan @denbonte

**Comment by deepakri201** [comment]
I've made some changes to the colormap as seen below, to make the vertebrae colors in particular more distinct: 

- Vertebra: the cervical, thoracic, and lumbar segments now contain different shades of a set color (red, blue, and yellow respectively). The colors in the thoracic vertebra are repeated from T1-T6 and T7-T12.  
- Ribs: colored to match the thoracic vertebra colors 
- A few other organ colors were modified so they're not visually close to the vertebra/ribs nearby. 

![image](https://github.com/ImagingDataCommons/Cloud-Resources-Workflows/assets/59979551/c70574de-f43a-401b-8cd0-d9eec31e464d)

One suggestion was to not make the corresponding ribs the same color as the vertebrae, and to use distinctive colors for all thoracic vertebrae. I would be happy to take any suggestions of what to try next!

**Comment by deepakri201** [comment]
Here is another example with the vertebrae all different colors: 

![image](https://github.com/ImagingDataCommons/Cloud-Resources-Workflows/assets/59979551/23101544-37e4-44ad-bd70-e1347f1c829c)
