### ISSUE TITLE
Clean up workflows to fix references

### ISSUE THREAD

**Issue by fedorov** [ImagingDataCommons/Cloud-Resources-Workflows#4]
The repo was migrated, but in some places the references to the artifacts in the prior location are still present (e.g., the one below). Those references should be fixed to point to the current repo. I do not think this is urgent at this point.

https://github.com/ImagingDataCommons/Cloud-Resources-Workflows/blob/1598c638d84726aa38b5b9896eca9b9746d45a7c/Terra/TotalSegmentator/splitWorkflow/twoVM.wdl#L109

**Comment by vkt1414** [comment]
Yes, I'm aware of that.
Also, could you take a look at the response we got from the dockstore community about the permissions? https://discuss.dockstore.org/t/dockstore-github-integration/7528/2

**Comment by fedorov** [comment]
Also Docker images sources, such as here:

https://github.com/ImagingDataCommons/Cloud-Resources-Workflows/blob/e2967bebf922b605406aac97c155fd63d3406814/SevenBridges/TotalSegmentator/splitWorkflow/twoVM.cwl#L187-L188
