### ISSUE TITLE
Add explanation of using Papermill parameterized notebooks

### ISSUE THREAD

**Issue by fedorov** [ImagingDataCommons/Cloud-Resources-Workflows#5]
For the key notebooks we are using, we should have documentation/preamble describing how they are parameterized, and some basic instructions on how to use them (e.g., example papermill command line), in the opening text cell of the notebook.

**Comment by vkt1414** [comment]
Sure. There are three ways one can use a notebook. 
1. Colab..just need to uncomment some cells to install some packages
2. as a Jupyter notebook: Steps for Colab+install more packages that are pre-installed in colab env
3. Inside a docker container/terra/sb-cgc: papermill command 

I can add these instructions to all notebooks

**Comment by fedorov** [comment]
and the instructions on what should be the format of the input parameters (ie, provide a snippet of a sample input CSV).

**Comment by vkt1414** [comment]
I think we can close this issue now that #35 is merged.
