### ISSUE TITLE
Reorganize Dockerfiles and improve image generation process

### ISSUE THREAD

**Issue by fedorov** [ImagingDataCommons/Cloud-Resources-Workflows#9]
Currently, all of the images from (functionally) different dockerfiles are deposited into the same Docker Hub repository. This can be confusing and may not be the best practice. We should do the following:
- reorganize the docker files to name them more intuitively and include description of the functionality
- set up automated docker image build process (probably, using GitHub Actions) and deposit each functionally distinctive image into an intuitively named DockerHub repo, tagged with the GitHub hash as a version

We also considered revisiting how docker images are generated, and reducing the number of docker images by installing task-specific packages as part of the notebook. This would definitely simplify maintenance and the process of integrating new tools by the users, but it will definitely result in a significant performance cost installing packages at runtime, so we discarded this idea.

**Comment by vkt1414** [comment]
@fedorov I was able to figure out the CI/CD process for docker images. 

There are five dockerfiles in our repo, and I came up with these names:

task1  ="imagingdatacommons/download_convert"
task2  ="imagingdatacommons/inference_totalseg"
task3  ="imagingdatacommons/radiomics"

tasks1and2  ="imagingdatacommons/download_convert_inference_totalseg"
end_to_end  ="imagingdatacommons/download_convert_inference_totalseg_radiomics"

Please let me know if they look ok. I'll reorganize the directory structure and update references whereever applicable
